# Вибір базового образу Nginx
FROM nginx

# Копіювання файлів вашого проекту у контейнер
COPY . /usr/share/nginx/html

# Вказівка команди для запуску веб-сервера Nginx
CMD ["nginx", "-g", "daemon off;"]
