version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"   # Порт PostgreSQL
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

  migrations:
    image: flyway/flyway
    volumes:
      - ./migrations:/flyway/sql   # Директорія з SQL-файлами міграцій
    environment:
      - FLYWAY_URL=jdbc:postgresql://db:5432/mydatabase
      - FLYWAY_USER=myuser
      - FLYWAY_PASSWORD=mypassword

  web:
    build: .
    ports:
      - "3000:3000"   
    depends_on:
      - db
      - migrations

volumes:
  postgres-data:   # Том для зберігання даних PostgreSQL
